import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './componants/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Todos',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
